### ISSUE TITLE
[Windows] Cannot open libraries from outside GCS

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#178] opened 2020-05-12 00:51 UTC
I'm not sure the actual cause of this but I suspect it has to do with parsing the message from Windows. When attempting to open a Library (such as advantages, equipment modifiers, etc) from Windows by double clicking in windows explorer, GCS will give a string of error dialogue boxes.
For example, when opening _Low Tech Equipment Modifiers.eqm_, it will give the following sequence of dialogue boxes:
Unable to open "Low".
Unable to open "Tech".
Unable to open "Equipment".
Unable to open "Modifiers.eqm".
(With the last one in the sequence being 'on top' of the others, so the user must close them in reverse order.)

**Comment by richardwilkes** [comment] 2020-05-12 04:15
Hmm... sounds like the packaging tool on Windows is assuming that paths passed to the executable will never have spaces in them, which of course isn’t the case. Unfortunately, that’s not something under my control — at least, I’m just using the Java 14 packager tool. I suppose there might be some tweaks I can do to the package after its built it...

**Comment by richardwilkes** [comment] 2020-05-16 17:08
This https://bugs.openjdk.java.net/browse/JDK-8235915 indicates the problem is fixed in Java 15. However, that has not yet been released. When it does get released, I'll move up to it and this problem should go away.

**Comment by richardwilkes** [comment] 2020-05-18 01:14
Decided to go ahead and use an early access version of JDK 15 to get this fix. It was also necessary to fix signing of macOS apps, so a win-win.

**Closed by richardwilkes** 2020-05-18 01:14 UTC
Labels: bug
