### ISSUE TITLE
Problem executing the progam with version 4.16

### ISSUE THREAD

**Issue by viniecastro** [richardwilkes/gcs#195] opened 2020-05-25 02:13 UTC
Greetings and salutations.
first of all i want to tanks you all for the amazing program, who is helping me so much in my games.
But i am having a problem with the new actualization i can't execute the program no matter what i do.

So....Help?

**Comment by richardwilkes** [comment] 2020-05-25 03:40
This is a duplicate of #192 -- please use the alternate installer for your system, which is linked to on the main GCS site.

**Closed by richardwilkes** 2020-05-25 03:40 UTC
