### ISSUE TITLE
Support for specialized DR

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#25] opened 2018-01-15 00:43 UTC
A primary example of this is the split DR that chainmail provides.

Having the option (maybe as a tooltip) to see damage type specific DR per location would be rather useful.

The many damage types that various armor protect against lead to quite the mess when one has to keep track of damage type specific DR manually - especially for the Ultra Tech armors.

**Comment by Hubok** [comment] 2020-04-25 19:36
This is definitely a stale enhancement request - but another thing to add to the pile when considering improving the DR calculations - front and rear DR. It might be easier to ignore for split DR, but might as well add it here.

**Comment by richardwilkes** [comment] 2021-02-20 00:06
Another one that is a subset of #218

**Comment by Human** [comment] 2021-09-19 14:58
Hi, @richardwilkes ! I think at some point the details of this request were lost during ticket maintenance.

This ticket requested support for split DR based on type. It's marked as a duplicate of ticket 218, which is closed, but split DR didn't make it into GCS. For example, Dreadnought Battlesuit (UT186) has split DR 200/150, but GCS only shows it as 150 DR.

Would you be ok with re-opening this?

**Closed** 2021-12-04 23:04 UTC
Labels: enhancement

**Comment by Human** [comment] 2021-12-20 00:20
:100:
