### ISSUE TITLE
Detail Editor is not rendering properly

### ISSUE THREAD

**Issue by GrifoCaolho** [richardwilkes/gcs#155] opened 2020-02-25 03:38 UTC
I did install the last working release of GCS and went to business on creating new characters.

When I open the Detail Editor (CTRL + I). the new window flicks and only the array shows, the rest of the itens being shrouded in black. I can hover over'em and click, and they will show, but had no luck looking for a solution.

So far, I have trying reinstalling, changing the resolution (1920x1080), the fonts, running both in compatibility and administrator mode.

Anyone has any idea on what is happening?

![image](https://user-images.githubusercontent.com/61443048/75212875-ff50fd80-5766-11ea-95d2-3a8d9578ea74.png)
Image above shows what happens when I open the Detail Editor.
 
![image](https://user-images.githubusercontent.com/61443048/75212897-155ebe00-5767-11ea-99ec-d203ec2b1d27.png)
Image above is after a few random clicks on where things should show up.

*EDIT: just noticed that I should have added. Running Windows 10.

**Comment by richardwilkes** [comment] 2020-02-25 16:20
Odd. I've seen this sort of behavior caused by two things:

- Running out of RAM on the graphics card (GCS itself isn't very taxing, but other programs could have reserved most of the available RAM, causing issues)
- Bad graphics drivers on Windows

Seeing any output on the command line would be useful -- but I don't believe Windows hooks up the console to "windowed" apps, which makes that problematic on that platform.

As a data point, it would be useful to update your graphics drivers to the latest, then reboot and launch GCS before launching anything else to see if the problem persists.

**Comment by GrifoCaolho** [comment] 2020-03-04 23:40
Hey, giving a heads up.

I tried openning GCS with every other possible application closed, to no results. I also did update every possible driver. It was also a fruitless effort (although I had one driver that was not up to date, so that is an upside). I am a bit skeptic that the problem might be RAM/VRAM (8 GB of the first, 4 GB of the later), but maybe it has to do with my videocard/CPU not being an usual/supported combination (my GPU is an AMD RX 680 4GB, while the CPU is an Intel Core i3 - 8300)?

I did notice that when I first open the Detail Editor, it flashes as if it was fully working, but then it turns to black. Don't know if that helps. I have been searching the web for people with the same problem, but couldn't find any further information.

Is there any information I can add that might be of help or any other course of action you suggest?

Thanks in advance, and sorry for bothering you with this strangely specific problem.

**Comment by richardwilkes** [comment] 2020-03-05 02:42
Just the information GCS might be writing to the console... but under Windows, I don't recall if that ever goes anywhere, thanks to their goofy split between "windowed" apps and "console" apps. I'm not near my Windows machines at the moment, so can't look. When I get a spare moment (and remember), I'll see what, if anything, can be done to retrieve the logs it normally writes.

**Comment by GrifoCaolho** [comment] 2020-03-05 03:47
No problem. I recognize it is a very specific problem that I've run into that may be specific to me. 
There is no particular hurry on my side, also. 

I will try downloading older versions of GCS in the meantime, if possible, and see if they work properly (I remember they did, but I may be misremembering things). I'll also look up on how to use the event viewer and try to see if I can get a proper log.

**Comment by richardwilkes** [comment] 2020-04-04 16:25
I'll leave this open for now. I don't see anything my code can do to fix this if it is indeed a driver/lack of graphics RAM issue (which is what I suspect), but I'm also not 100% sure that's what it is. Unfortunately, I've not been able to replicate it, which makes it particularly difficult to diagnose.

**Comment by richardwilkes** [comment] 2020-05-26 00:19
Closing since no reproduction steps are available. Should steps be found, please add them to this report and reopen and I'll take a look.

**Closed by richardwilkes** 2020-05-26 00:19 UTC
Labels: bug, can't replicate
