### ISSUE TITLE
View changes to First Character Sheet in list after committing changes to advantages.

### ISSUE THREAD

**Issue by jcklemme** [richardwilkes/gcs#554] opened 2022-09-27 19:57 UTC
I have included a video of it happening on the discord server to better explain the issue.
When I change an advantage and commit the change, the view changes to the first sheet in the "pile" after I make the commit, regardless of what sheet I was looking at.  I'm assuming this is not intended.

**Comment by richardwilkes** [comment] 2022-09-27 22:47
Duplicate of #552

**Closed by richardwilkes** 2022-09-27 22:47 UTC
Labels: bug, duplicate
