### ISSUE TITLE
Split DR

### ISSUE THREAD

**Issue by zelder** [richardwilkes/gcs#268] opened 2020-10-09 20:54 UTC
There is a problem that DR can be different - from fire, from piersing attacks, but in GCS there is no difference between these DRs. Also, when I wear armor, it has a different DR from different types of damage, but it is impossible to write it down correctly.

I would like to have several DR columns for different types of damage, even if only one is displayed, but with the ability to open them or switch from one to another for viewing.

**Comment by richardwilkes** [comment] 2020-10-09 21:50
Duplicate of #25

**Comment by zelder** [comment] 2020-10-09 22:02
No so duplicate - a talk some another. Not only back and face sides

**Comment by richardwilkes** [comment] 2020-10-09 22:22
#25 discusses more than just back/front. Feel free to add more detail to that issue. I do not want multiple issues for essentially the same thing.

**Closed** 2021-09-19 15:05 UTC
Labels: duplicate
