### ISSUE TITLE
[Feature Request] Money Tracking

### ISSUE THREAD

**Issue by DeNarr** [richardwilkes/gcs#99] opened 2019-05-14 21:09 UTC
A better form of money tracking would be greatly appreciated. There's currently no good way to put in how much money you start with, spend the money, and see how much you have left.

**Comment by richardwilkes** [comment] 2022-11-06 00:36
I'm generally against this, as the standard equipment support and summary display of equipment value and weight covers what is needed. Even if I did decide to do something here, the main issue would be how to determine exactly what to record. Just because I added something to my sheet, for example, doesn't mean its value should be deducted from my money -- it could have been a gift or something I found. Same thing for removals or quantity changes. Essentially, there would be no way to automatically determine the right thing to do, which would mean annoying dialogs popping up with every single change to equipment to ask the user what was intended.

I'm going to close this out. If you have a good suggestion on how this could be managed, feel free to re-open it and add the details on how you think it could work.

**Closed by richardwilkes** 2022-11-06 00:36 UTC
Labels: enhancement
