### ISSUE TITLE
Allow DR to be applied separately to left or right limb/extremity

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#296] opened 2021-02-09 06:36 UTC
Pretty simple request. Apologize if this has been said before, but I checked and didn't see one.

**Comment by richardwilkes** [comment] 2021-02-09 09:52
There are already several permutations of additional DR support requested. As with all of them, the issue is a lack of space to display the information on the sheet in a reasonable way. If I did the things that have been asked, at least half the sheet would be dedicated to just displaying hit location DR permutations, which isn’t acceptable.

I’m not against adding the support — but it won’t happen until a reasonable display is come up with that I can implement at the same time.

**Comment by kaldrich001** [comment] 2021-02-09 19:46
Wait, what? Right/left leg/arm are already displayed in the hit location section. You just can't separately add DR for them.

**Comment by richardwilkes** [comment] 2021-02-09 20:02
While that's true, there are many more body types, some of which don't have those same distinctions, or have them in greater numbers, e.g. left and right aren't meaningful for an octopod.

**Comment by richardwilkes** [comment] 2021-02-19 23:58
Duplicate of #83

**Closed by richardwilkes** 2021-02-19 23:58 UTC
Labels: duplicate, enhancement
