### ISSUE TITLE
Feature: Search function

### ISSUE THREAD

**Issue by DigitalNinja68** [richardwilkes/gcs#555] opened 2022-09-27 20:25 UTC
Request: In the previous version, when searching through skills/equipment/etc it only showed matches. I think this is better than the current functionality where it highlights the item in the existing table.

**Comment by ingeanus** [comment] 2022-09-30 01:49
This is especially noticeable in the two cases of:

- Trying to search for something that you don't exactly remember the name of, as now you have to click through an entire list of semi-matches in order to confirm if you are searching correctly.
- Trying to filter or search by a widespread name, such as "Technique" or "Electronics Operation", as you now have to click to examine every single option individually, as opposed to being able to appraise the entire groups in bulk.

**Comment by richardwilkes** [comment] 2022-10-02 02:04
Duplicate of #534

**Closed by richardwilkes** 2022-10-02 02:04 UTC
Labels: duplicate, enhancement
