### ISSUE TITLE
Crash under 4.16.0

### ISSUE THREAD

**Issue by chrono280** [richardwilkes/gcs#196] opened 2020-05-25 20:04 UTC
Cannot run after updating to 4.16.0. See crashlog attached
[hs_err_pid14520.log](https://github.com/richardwilkes/gcs/files/4678683/hs_err_pid14520.log)

**Comment by richardwilkes** [comment] 2020-05-25 20:06
This is a duplicate of #192 -- please use the alternate installer for your system, which is linked to on the main GCS site.

**Closed by richardwilkes** 2020-05-25 20:06 UTC
