### ISSUE TITLE
GCS 5.10: Printing failed; Error code 0x0400

### ISSUE THREAD

**Issue by Human** [richardwilkes/gcs#694] opened 2023-05-06 13:10 UTC
I can export to a PDF and print that way, but I am no longer able to print directly. I get the error in the issue description. Please let me know how I can provide relevant logs.

Kubuntu 23.04, GCS 5.10

**Comment by richardwilkes** [comment] 2023-05-07 16:31
This a duplicate of #593. Unfortunately, this error code usually means the printer doesn't support the AirPrint protocol properly or is using one of the security features which I've not implemented support for, effectively preventing printing to the printer.

I've had good luck with a handful of HP printers I've tested this code on, but don't have access to much beyond those. If you'd like to diagnose the problem further, hit me up on the GCS Discord and I can put together a version of GCS that dumps some additional data about what is going wrong. I suspect there will be nothing I will be able to do about it, but its possible that the additional detail will point to something that I can actually fix.

**Closed by richardwilkes** 2023-05-07 16:31 UTC
Labels: bug, wontfix
