### ISSUE TITLE
GCS glitching out

### ISSUE THREAD

**Issue by Jesseman1** [richardwilkes/gcs#213] opened 2020-06-07 21:48 UTC
I've had this problem with the GCS ever since first installing it. I honestly can't tell if it's a problem with the GCS itself or maybe the version of Java i'm using. Entirely at random the GCS will start pasting copies of the page over any editable or clickable area. I can't find any specific trigger but it most often happens while editing traits/skills such as adding notes or modifiers. The only way to make it stop is by closing the program, all I can do is launch it again and hope I can get more work done before it breaks again.
![GCS Glitch](https://user-images.githubusercontent.com/26986519/83980849-ec61d380-a8e6-11ea-876b-64be1cdb0e5f.png)

**Comment by richardwilkes** [comment] 2020-06-07 21:56
This looks the same as #197. These are one of two things:
1. An exception in the UI is being thrown and not handled.
2. Your graphics card is running out of RAM.

If it is the first one, attaching the GCS log file can help if it has any content. If you're running on Windows, then the file can be found at `%LOCALAPPDATA%\GCS\error.log`.

If it is the second one, there is nothing I can do.

**Comment by Jesseman1** [comment] 2020-06-07 22:05
This has happened in another program, though I can't imagine it's my Graphics Card, I'm using a GTX 1650 and have no other graphic intensive programs running. As for the error log, I'm not finding a GCS folder in Local, only gcs.pref

**Comment by richardwilkes** [comment] 2020-06-07 22:10
OK, if you're not seeing an error log, then that means GCS isn't aware of any problems and it is most likely the graphics card or its driver that is the problem.

Certainly if you can provide reproducible steps, I'm happy to take a look. But barring a reproducible case, I have no way to examine what is occurring.

**Comment by Jesseman1** [comment] 2020-06-07 22:15
I don't know, I did it again on the main page without any files being open, i was just looking at the File, Item, and Help tabs. Its been getting worse and really frustrating me. How can the graphics card be running out of VRAM without any games running?

**Comment by richardwilkes** [comment] 2020-06-07 22:17
I'm afraid I don't know. There are a very small handful of users out there that have reported this issue and they all run Windows. Given that it is a graphics glitch, I'm guessing that the graphics card or its driver is the cause since it doesn't occur for most everyone else.

**Comment by Jesseman1** [comment] 2020-06-07 22:30
Just updated my graphics driver to the latest version and it's *still* breaking.

**Comment by Jesseman1** [comment] 2020-06-07 22:31
How much VRAM does this program use!?

**Comment by richardwilkes** [comment] 2020-06-07 22:32
Not much -- just enough to buffer each window.

**Comment by Jesseman1** [comment] 2020-06-07 22:34
the GTX 1650 has 2GB of VRAM, so it should be handling this program without any problems

**Comment by richardwilkes** [comment] 2020-06-07 22:39
2 GB of VRAM is actually quite small nowadays. Most OS's will consume a fair amount just buffering the desktop windows, depending on the size of your display, let alone what other programs running might be consuming. As an example, my machine has roughly 8 GB of VRAM in use nearly constantly, no matter what I'm doing. I have 3x 5K displays attached, though, so that accounts for a large amount of screen real estate that it needs to keep buffered even when nothing else is happening. That said, it very well could be something else -- I just can't tell without seeing it in person or getting a log from your machine that explicitly shows that there is something wrong and where it happened.

**Comment by Jesseman1** [comment] 2020-06-07 22:42
What should I do then? I only got this graphics card last year and I dont want to have to buy a new one already.

**Comment by richardwilkes** [comment] 2020-06-07 22:45
I don't have a good answer for you. I am about to make another small release this evening and I'll turn on a bit more capturing logic in case there *are* exceptions being thrown that aren't being caught and logged. You might want to wait for that release and give it a try... then look for a log file it the problem recurs.

**Comment by Jesseman1** [comment] 2020-06-07 22:48
ok

**Comment by peruses** [comment] 2020-06-08 00:17
To test for VRAM buffer issues adjust your screen resolution down a few steps, 2g can be barly adequate for running 4k displays depending. If you are pushing 4k on that card and don't need it adjusting down to 1080p should make your whole system feel snappier.

**Comment by Jesseman1** [comment] 2020-06-08 02:10
My monitor is running 1920x1080 resolution

**Comment by peruses** [comment] 2020-06-08 20:24
You shouldn't have an issue at 1080, but can give a shot  at 720ish, i forget if the windows task manager displays vram usage it's been a while now since i had to fight with such things

**Comment by richardwilkes** [comment] 2020-06-18 18:41
Lacking further info, I'm closing this out. If you can provide an error log that shows an issue, I'm happy to take a look.

**Closed by richardwilkes** 2020-06-18 18:41 UTC
Labels: bug
