### ISSUE TITLE
Stat customization broken

### ISSUE THREAD

**Issue by peruses** [richardwilkes/gcs#398] opened 2021-11-30 06:11 UTC
The the ability to create custom stats including recosting stats and divorcing will and perception from IQ seems to have broken with recent updates. I discovered the issue when I tried to apply a .gas file to some old character sheets to adapt them to my new campaign and instead of applying the custom setup it returned to basic set stat costs and dependencies. I confirmed the problem existed at least as far back as version 4.34 by testing on my laptop. The per sheet settings, attribute and body type are all greyed out on version 4.34 4.41 and 4.5.

I will send you a .gas file via discord from peruses#1126 which should result in the custom stat costs below. Thankyou.

Perception and Will will be divorced from IQ and paid for separately

Basic speed will be equal to (Perception+Dex)/4

Stat costs per level:
IQ 15
Strength 10
Dex 20
HT 10 
Perception 10
will 5
Fp 3
Hp 2
Basic speed 5/.25
Basic Move 5

**Comment by peruses** [comment] 2021-11-30 06:18
Silly of me I forgot to give system information windows 10 home build 19043.1348

**Comment by richardwilkes** [comment] 2022-07-04 18:21
@peruses is this still a problem? Apparently I was not able to reproduce it. Please attach files to illustrate the problem if it still exists. If I don't see a reply soon, I'll assume this isn't an issue anymore and close it.

**Closed** 2022-07-09 20:03 UTC
Labels: bug, can't replicate
