### ISSUE TITLE
Wrapping of advantage and advantage modifiers done wrong when exporting

### ISSUE THREAD

**Issue by RetardedMermaid** [richardwilkes/gcs#319] opened 2021-03-27 01:34 UTC
**Description:**
In the Advantages section, after exporting (to either PDF or Image) part of the text of the note goes **under** the columns cost and reference. The issue doesn't manifest in the UI of GCS itself (the notes wrap correctly).

**Local System Information:**
- GCS version: 4.29
- System Information
  - Edition	Windows 10 Pro
  - Version	20H2
  - Installed on	‎6/‎17/‎2020
  - OS build	19042.867
  - Experience	Windows Feature Experience Pack 120.2212.551.0
- Output of java -version:
  - java version "1.8.0_281"
  - Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
  - Java HotSpot(TM) Client VM (build 25.281-b09, mixed mode, sharing)

**How to Reproduce**
1. Create or Open character in GCS.
2. Drag an advantage into the character's advantage section.
3. Double click the advantage. On the field labeled _Notes_ paste any text that would need proper line wrapping, such as the one provided below:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu suscipit sem, vitae elementum mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum vehicula consectetur tempor. Vestibulum nec metus venenatis, facilisis dui a, viverra dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce tincidunt eget erat in sagittis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut id urna finibus, hendrerit metus sed, elementum neque. In blandit justo vitae est mollis, vitae fringilla nulla pharetra.

4. Go to File -> Export To... -> click Export to PDF.

**Comment by richardwilkes** [comment] 2021-04-12 03:13
I'm unable to reproduce this on macOS. I've not yet tried it on Windows. I will at some point... in the meantime, this could be a font problem rather than anything specific with GCS. Worth trying other fonts to verify.

**Comment by richardwilkes** [comment] 2021-04-12 03:43
Just tried this on my Windows 10 box... and unable to reproduce it there, too.

I noticed you mention you're running an old version of Java... GCS is packaged with its own (much newer) version of Java. If you are somehow using the older version, that may be the issue. Anyway, I'm going to close this as unreproducible -- if you have further steps that can be tried to illustrate the problem, add them to this bug report and re-open it and I'll take another look.

**Closed by richardwilkes** 2021-04-12 03:43 UTC
Labels: bug
