### ISSUE TITLE
Windows will not start

### ISSUE THREAD

**Issue by LanceLake** [richardwilkes/gcs#194] opened 2020-05-24 05:57 UTC
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=9120, tid=12452
#
# JRE version:  (15.0+23) (build )
# Java VM: OpenJDK 64-Bit Server VM (15-ea+23-1098, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
#

---------------  S U M M A R Y ------------

Command Line: -Dhttps.protocols=TLSv1.2,TLSv1.1,TLSv1 -Dsun.java2d.dpiaware=false -Djdk.module.main=com.trollworks.gcs com.trollworks.gcs/com.trollworks.gcs.app.GCS

Host: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 8 cores, 15G,  Windows 10 , 64 bit Build 18362 (10.0.18362.778)
Time: Sat May 23 22:35:14 2020 Pacific Daylight Time elapsed time: 0.061048 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x000001591c722800):  JavaThread "Unknown thread" [_thread_in_vm, id=12452, stack(0x0000002a20100000,0x0000002a20200000)]

Stack: [0x0000002a20100000,0x0000002a20200000],  sp=0x0000002a201fef78,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), data execution prevention violation at address 0x0000000000000000

Registers:
RAX=0x000001591cadfeac, RBX=0x000001593a931800, RCX=0x000001591cadfeac, RDX=0x000000000000034b
RSP=0x0000002a201fef78, RBP=0x0000002a201ff090, RSI=0x000001591cadfe8f, RDI=0x000001591cadfe8f
R8 =0x000001593a931800, R9 =0x00000000000005ce, R10=0x0000002a201feff0, R11=0x0000002a201feed0
R12=0x00000000000005ce, R13=0x000001591c722800, R14=0x000001591c726710, R15=0x000001591c726710
RIP=0x0000000000000000, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x0000002a201fef78)
0x0000002a201fef78:   00007ffe6a24182f 000001593a931800
0x0000002a201fef88:   00007ffe6a241873 00000000000005ce
0x0000002a201fef98:   0000000000000000 0000002a201fefd8
0x0000002a201fefa8:   0000000000000000 000001591cadfe8f
0x0000002a201fefb8:   00007ffe6a241495 000001593a931800
0x0000002a201fefc8:   0000002a201ff090 000001591cadfe8f
0x0000002a201fefd8:   0000000000000000 0000002a201ff090
0x0000002a201fefe8:   00007ffe2093582a 0000002acafefafa
0x0000002a201feff8:   000000000000034b 00000000000005ce
0x0000002a201ff008:   ffffffff00000007 0000000086183d01
0x0000002a201ff018:   000099da2e9ec02e 00000000000005ce
0x0000002a201ff028:   000001591c726710 000001591c723480
0x0000002a201ff038:   000001591aca37a0 0000000000215291
0x0000002a201ff048:   0000000000000368 000001591cadfe8f
0x0000002a201ff058:   00007ffe6a241ed3 0000015939f68e90
0x0000002a201ff068:   0000000000000016 0000000000000000 

Instructions: (pc=0x0000000000000000)
0xffffffffffffff00:   

---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x00007ffe20ced068, length=0, elements={
}

Java Threads: ( => current thread )

Other Threads:
  0x000001591c775000 GCTaskThread "GC Thread#0" [stack: 0x0000002a20200000,0x0000002a20300000] [id=18404]
  0x000001591c788000 ConcurrentGCThread "G1 Main Marker" [stack: 0x0000002a20300000,0x0000002a20400000] [id=16628]
  0x000001591c789000 ConcurrentGCThread "G1 Conc#0" [stack: 0x0000002a20400000,0x0000002a20500000] [id=17824]
  0x0000015939f63000 ConcurrentGCThread "G1 Refine#0" [stack: 0x0000002a20500000,0x0000002a20600000] [id=6748]
  0x0000015939f64000 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x0000002a20600000,0x0000002a20700000] [id=17940]

=>0x000001591c722800 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=12452, stack(0x0000002a20100000,0x0000002a20200000)]

Threads with active compile tasks:

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None

Heap address: 0x0000000702000000, size: 4064 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
Narrow klass base: 0x0000000800000000, Narrow klass shift: 0
Compressed class space size: 1073741824 Address: 0x0000000800000000

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Classes unloaded (0 events):
No events

Classes redefined (0 events):
No events

Internal exceptions (0 events):
No events

Events (2 events):
Event: 0.044 Loaded shared library C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\java.dll
Event: 0.052 loading class java/lang/Object

Dynamic libraries:
0x00007ff784d50000 - 0x00007ff784dd1000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\GCS.exe
0x00007ffe79440000 - 0x00007ffe79630000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffe77b60000 - 0x00007ffe77c12000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffe767e0000 - 0x00007ffe76a84000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffe78ba0000 - 0x00007ffe78d34000 	C:\WINDOWS\System32\USER32.dll
0x00007ffe76700000 - 0x00007ffe76721000 	C:\WINDOWS\System32\win32u.dll
0x00007ffe77ca0000 - 0x00007ffe77cc6000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffe76530000 - 0x00007ffe766c4000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffe77300000 - 0x00007ffe7739e000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffe763d0000 - 0x00007ffe764ca000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffe78140000 - 0x00007ffe78824000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffe772b0000 - 0x00007ffe772fa000 	C:\WINDOWS\System32\cfgmgr32.dll
0x00007ffe78d50000 - 0x00007ffe78df9000 	C:\WINDOWS\System32\shcore.dll
0x00007ffe79360000 - 0x00007ffe793fe000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffe78a80000 - 0x00007ffe78ba0000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffe77d50000 - 0x00007ffe78086000 	C:\WINDOWS\System32\combase.dll
0x00007ffe77210000 - 0x00007ffe77290000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffe76a90000 - 0x00007ffe7720e000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffe78e00000 - 0x00007ffe78e97000 	C:\WINDOWS\System32\sechost.dll
0x00007ffe79110000 - 0x00007ffe791b3000 	C:\WINDOWS\System32\advapi32.dll
0x00007ffe763a0000 - 0x00007ffe763c3000 	C:\WINDOWS\System32\profapi.dll
0x00007ffe76330000 - 0x00007ffe7637a000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffe76300000 - 0x00007ffe76310000 	C:\WINDOWS\System32\UMPDC.dll
0x00007ffe77aa0000 - 0x00007ffe77af2000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffe76310000 - 0x00007ffe76321000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffe77290000 - 0x00007ffe772a7000 	C:\WINDOWS\System32\cryptsp.dll
0x00007ffe790e0000 - 0x00007ffe7910e000 	C:\WINDOWS\System32\IMM32.DLL
0x00007ffe5b390000 - 0x00007ffe5b3a8000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\jli.dll
0x00007ffe685c0000 - 0x00007ffe68669000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.836_none_2a2600ea466b531c\COMCTL32.dll
0x00007ffe6b040000 - 0x00007ffe6b057000 	C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
0x00007ffe5b370000 - 0x00007ffe5b389000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\vcruntime140.dll
0x00007ffe6c0c0000 - 0x00007ffe6c0cc000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\vcruntime140_1.dll
0x00007ffe55be0000 - 0x00007ffe55c71000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\msvcp140.dll
0x00007ffe20260000 - 0x00007ffe20d84000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\server\jvm.dll
0x00007ffe78d40000 - 0x00007ffe78d48000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffe74e50000 - 0x00007ffe74e59000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffe6c5a0000 - 0x00007ffe6c5c4000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffe719a0000 - 0x00007ffe719aa000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffe792f0000 - 0x00007ffe7935f000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffe6c570000 - 0x00007ffe6c59d000 	C:\WINDOWS\SYSTEM32\winmmbase.dll
0x00007ffe6a240000 - 0x00007ffe6a24a000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\jimage.dll
0x00007ffe74c30000 - 0x00007ffe74e24000 	C:\WINDOWS\SYSTEM32\DBGHELP.DLL
0x00007ffe70100000 - 0x00007ffe7012a000 	C:\WINDOWS\SYSTEM32\dbgcore.DLL
0x00007ffe5a2f0000 - 0x00007ffe5a315000 	C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\java.dll

dbghelp: loaded successfully - version: 4.0.5 - missing functions: none
symbol engine: initialized successfully - sym options: 0x614 - pdb path: .;C:\Games\Tabletop Gaming\RPGs\GURPS Characters;C:\WINDOWS\SYSTEM32;C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin;C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.836_none_2a2600ea466b531c;C:\Games\Tabletop Gaming\RPGs\GURPS Characters\runtime\bin\server

VM Arguments:
jvm_args: -Dhttps.protocols=TLSv1.2,TLSv1.1,TLSv1 -Dsun.java2d.dpiaware=false -Djdk.module.main=com.trollworks.gcs 
java_command: com.trollworks.gcs/com.trollworks.gcs.app.GCS
java_class_path (initial): <not set>
Launcher Type: SUN_STANDARD

[Global flags]
     intx CICompilerCount                          = 4                                         {product} {ergonomic}
     uint ConcGCThreads                            = 2                                         {product} {ergonomic}
     uint G1ConcRefinementThreads                  = 8                                         {product} {ergonomic}
   size_t G1HeapRegionSize                         = 2097152                                   {product} {ergonomic}
    uintx GCDrainStackTargetSize                   = 64                                        {product} {ergonomic}
   size_t InitialHeapSize                          = 266338304                                 {product} {ergonomic}
   size_t MarkStackSize                            = 4194304                                   {product} {ergonomic}
   size_t MaxHeapSize                              = 4261412864                                {product} {ergonomic}
   size_t MaxNewSize                               = 2556428288                                {product} {ergonomic}
   size_t MinHeapDeltaBytes                        = 2097152                                   {product} {ergonomic}
   size_t MinHeapSize                              = 8388608                                   {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5839372                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122909434                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122909434                              {pd product} {ergonomic}
    uintx ReservedCodeCacheSize                    = 251658240                              {pd product} {ergonomic}
     bool SegmentedCodeCache                       = true                                      {product} {ergonomic}
   size_t SoftMaxHeapSize                          = 4261412864                             {manageable} {ergonomic}
     bool UseCompressedClassPointers               = true                                 {lp64_product} {ergonomic}
     bool UseCompressedOops                        = true                                 {lp64_product} {ergonomic}
     bool UseG1GC                                  = true                                      {product} {ergonomic}
     bool UseLargePagesIndividualAllocation        = false                                  {pd product} {ergonomic}

Logging:
Log output configuration:
 #0: stdout all=warning uptime,level,tags
 #1: stderr all=off uptime,level,tags

Environment Variables:
PATH=C:\Program Files (x86)\Python2.7.13\;C:\Program Files (x86)\Python2.7.13\Scripts;C:\Users\Joseph\AppData\Roaming\Python\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\CMake\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Joseph\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\Users\Joseph\AppData\Roaming\npm;
USERNAME=Joseph
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10 , 64 bit Build 18362 (10.0.18362.778)
OS uptime: 2 days 9:38 hours

CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 94 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, vzeroupper, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx, fma, clflush, clflushopt

Memory: 4k page, system-wide physical 16252M (8762M free)
TotalPageFile size 32636M (AvailPageFile size 21248M)
current process WorkingSet (physical memory assigned to process): 15M, peak: 15M
current process commit charge ("private bytes"): 331M, peak: 331M

vm_info: OpenJDK 64-Bit Server VM (15-ea+23-1098) for windows-amd64 JRE (15-ea+23-1098), built on May 13 2020 16:40:06 by "mach5one" with unknown MS VC++:1925

END.

**Comment by richardwilkes** [comment] 2020-05-24 06:36
This is a duplicate of #192 -- please use the alternate installer for your system

**Closed by richardwilkes** 2020-05-24 06:36 UTC
