### ISSUE TITLE
Windows Installer Adds Shell Open Command Without Quotes

### ISSUE THREAD

**Issue by RevenantBob** [richardwilkes/gcs#143] opened 2019-12-28 18:10 UTC
Reproduced in Version 4.13.3 on Windows 10

**Reproduction**

1. Install from MSI
2. Create a character with a space in the name such as "Bob Ross.gcs"
3. Right click the file in explorer and select "Open With"
4. Select GURPS Character assistant

**Outcome**
GCS will fail to open the file.

**Expected Result**
GCS Opens the file.

**Possible Resolution**
The associated registry keys for opening files with GCS do not have quotations around the argument supplied as %1. This is true of all associated file types, (.gcs, .gct, etc).

_Example:_

The registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\progid57c16793feb03acc9b7d258aeda3253d\shell\open\command" contains:

"C:\Program Files\GURPS Character Sheet\GURPS Character Sheet.exe" %1

It should contain:

"C:\Program Files\GURPS Character Sheet\GURPS Character Sheet.exe" "%1"

**Comment by richardwilkes** [comment] 2019-12-28 18:18
This is a duplicate of https://github.com/richardwilkes/gcs/issues/139. I was aware of what the issue was, just not sure how to fix it with the current tooling I'm using to create the package for Windows... and was hoping the Java guys would get their acts together and release the darn thing -- still can't believe they removed what I view as an essential tool without a replacement.

**Comment by richardwilkes** [comment] 2019-12-28 19:09
Looks like this issue claims to be fixed in JDK 15 build 2... https://bugs.openjdk.java.net/browse/JDK-8235915

Of course, I thought I was taking a chance by using the unreleased JDK 14... but this one is even sketchier. (sigh) Anyway, I'll give this a whirl and see if it fixes the issue for me.

**Comment by richardwilkes** [comment] 2019-12-28 21:14
Seems fixed when using the jpackage tool from JDK 15 build 2.

**Closed by richardwilkes** 2019-12-28 21:14 UTC
